stages:
  - deploy

deploy_minilims:
  stage: deploy
  script:
  - sudo cp -r ${CI_PROJECT_DIR}/. /opt/ngsweb
  - sudo /bin/systemctl restart ngsweb.service
  only:
    - minilims_creators
  tags:
    - test2

# There is currently no straightforward way to run a ci job on all registered runners
# We use the 'parallel' option, but the number of servers in an environment has to be configured manually.

deploy_test:
  stage: deploy
  script:
  - sudo cp -r ${CI_PROJECT_DIR}/. /opt/ngsweb
  - sudo /bin/systemctl restart ngsweb.service
  rules:
    - when: manual
  tags:
    - test

deploy_acc:
  stage: deploy
  script:
  - sudo cp -r ${CI_PROJECT_DIR}/. /opt/ngsweb
  - sudo /bin/systemctl restart ngsweb.service
  only:
    - master
  tags:
    - acc

deploy_production:
  stage: deploy
  script:
  - sudo cp -r ${CI_PROJECT_DIR}/. /opt/ngsweb
  - sudo /bin/systemctl restart ngsweb.service
  only:
    - release
  tags:
    - prod
