stages:
  - deploy

deploy_test:
  stage: deploy
  script:
  - /opt/miniconda3/bin/conda env update -n base -f ${CI_PROJECT_DIR}/myflask.yaml
  - cp -r ${CI_PROJECT_DIR}/* /opt/ngsweb
  - sudo /bin/systemctl restart ngsweb.service
  only:
    - master
  tags:
    - test

deploy_production:
  stage: deploy
  script:
  - /opt/miniconda3/bin/conda env update -n base -f ${CI_PROJECT_DIR}/myflask.yaml
  - cp -r ${CI_PROJECT_DIR}/* /opt/ngsweb
  - sudo /bin/systemctl restart ngsweb.service
  only:
    - release
  tags:
    - prod
