stages:
  - deploy

deploy_minilims:
  stage: deploy
  script:
  - cp -r ${CI_PROJECT_DIR}/* /opt/ngsweb
  - sudo /bin/systemctl restart ngsweb.service
  only:
    - minilims_creators
  tags:
    - test2

# There is currently no straightforward way to run a ci job on all registered runners
# We use the 'parallel' option, but the number of servers in an environment has to be configured manually.

deploy_test:
  stage: deploy
  script:
  - cp -r ${CI_PROJECT_DIR}/* /opt/ngsweb
  - sudo /bin/systemctl restart ngsweb.service
  only:
    - master
  parallel: 2
  tags:
    - test
    - 0${CI_NODE_INDEX}

deploy_production:
  stage: deploy
  script:
  - cp -r ${CI_PROJECT_DIR}/* /opt/ngsweb
  - sudo /bin/systemctl restart ngsweb.service
  only:
    - release
  tags:
    - prod
