version: '3'
services:

  # note; symlink docker-compose.development.yml to
  # docker-compose.override.yml when developing.

  ngsweb:
    build: .
    image: ngsweb
    environment:
      FLASK_APP: 'app'
      PORT: '8080'
    entrypoint: /bin/bash -c ". /venv/bin/activate && uwsgi --ini ngsweb.ini --http 0.0.0.0:3456"
    ports:
      - 3333:3456
    volumes:
      - ./instance/:/ngsweb/instance/
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"
        tag: "ngsweb-docker"
        syslog-format: "rfc3164"
        syslog-facility: "local6"
    networks:
      - ngsweb_network

networks:
  ngsweb_network:
    driver: bridge