[uwsgi]
module = app.ngsweb:create_app()
callable = app
wsgi-disable-file-wrapper

harakiri = 1800
harakiri-verbose = true
max-requests = 1000
min-worker-lifetime = 60
max-worker-lifetime = 3600

master = true
processes = 20

die-on-term = true
enable-threads = true

#chdir=/home/adm-verhager/myproject
chdir=/ngsweb

