[uwsgi]
module = app
callable = app
wsgi-disable-file-wrapper

master = true
processes = 5

socket = ngsweb.sock
chmod-socket = 660
vacuum = true

die-on-term = true

#chdir=/home/adm-verhager/myproject
chdir=/opt/ngsweb
