[uwsgi]
module = app
callable = app
wsgi-disable-file-wrapper
catch-exceptions = true

master = true
processes = 4

; socket = ngsweb.sock
; chmod-socket = 660
; vacuum = true

die-on-term = true
enable-threads = true

