[uwsgi]
module = app
callable = app
wsgi-disable-file-wrapper
catch-exceptions = true

harakiri = 60
harakiri-verbose = true
max-requests = 1000
min-worker-lifetime = 60
max-worker-lifetime = 3600

master = true
processes = 4

; socket = ngsweb.sock
; chmod-socket = 660
; vacuum = true

die-on-term = true
enable-threads = true

; metric-alarm = key=socket.0.listen_queue,value=1,alarm=listen_queue_full
; alarm = listen_queue_full cmd:systemctl restart ngsweb

