[uwsgi]
#module = idms.web.wsgi:app
module = idms.web:create_app()

# Bind directly to HTTP inside container
# http-socket = 0.0.0.0:3333

callable = app
wsgi-disable-file-wrapper

# Timeouts & Workers
harakiri = 1800
harakiri-verbose = true
max-requests = 1000
min-worker-lifetime = 60
max-worker-lifetime = 3600
max-worker-lifetime-delta = 900

master = true
processes = 20

die-on-term = true
enable-threads = true
