[uwsgi]
#wsgi-file = idms/web/wsgi.py
module = idms.web:create_app()
callable = app
wsgi-disable-file-wrapper
catch-exceptions = true

harakiri = 1800
harakiri-verbose = true
max-requests = 1000
min-worker-lifetime = 60
max-worker-lifetime = 3600
max-worker-lifetime-delta = 900

master = true
processes = 2
threads = 2
enable-threads = true

die-on-term = true
