from irods.models import Collection, DataObject

ATTR_TIERING_GROUP = 'sys::tiering::group'
ATTR_RESOURCE_PREFIX = 'sys::resource::'
ATTR_RESOURCE_ENABLED = 'sys::resource::enabled'
ATTR_RESOURCE_AVAILABLE = 'sys::resource::available'
ATTR_RESOURCE_TAR = 'sys::resource::tar'
ATTR_RESOURCE_ONLINE = 'sys::resource::online'

FEATURES = {
    'actions': ('Show actions pane', 'true'),
    'jobs': ('Show process configuration and job status page', 'true'),
    'projects': ('Show project configuration pages', 'true'),
    'provenance': ('Show and manage data provenance', 'true'),
    'reference': ('Show reference data configuration', 'false'),
    'sharing': ('Configure datasets that need to be shared externally', 'false'),
    'minilims': ('Show ONT samplesheet configuration interface', 'false'),
    'treeview': ('Use treeview in collection browser instead of project list', 'false'),
    'metadataunits': ('Show option to display unit column in metadata table', 'false')
}

COLL_KEY_MAP = {
    'name': Collection.name,
    'create_time': Collection.create_time,
    'size': Collection.name, # Collections do not have a size property
    'owner_name': Collection.owner_name
}

DATA_KEY_MAP = {
    'name': DataObject.name,
    'create_time': DataObject.create_time,
    'size': DataObject.size,
    'owner_name': DataObject.owner_name
}

# Constansts that define the JOB VIEW
JOB_PAGE_SIZE = 25

# Border colors of shapes
DEFAULT_COLOR = '#000000'
SYS_INVALID_COLOR = '#ff3333'
USER_INVALID_COLOR = "#b51c1c"

# Penwidth of Shape Borders
DEFAULT_PENWIDTH = '1'
SELECTED_PENWIDTH = '3'
SELECTED_FILE_IN_COLL_PENWIDTH = '2'

# Fontsize in Shapes
DEFAULT_FONTSIZE = '8'
DEFAULT_FONTSIZE_BIG = '9'
SELECTED_FONTSIZE = '10'

# Variables for Graphs
SVG_PATH = 'app/static/svg'
ATTR_GRAPH_FONT = "'Source Sans Pro',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol'"

# Constants for graphical layout, shapes and colors, also used to create a legend.
ORDER ='order'
TYPE = 'type'
ARROWHEAD = 'arrowhead' 
NAME = 'name'
SHAPE = 'shape'
SHAPE_PROCESS = 'shape_process'
COLOR = 'color'
FILLCOLOR = 'fillcolor'
TABLECLASS = 'tableclass'
STYLE = 'style'
LABEL = 'label'
XLABEL = 'xlabel'
TOOLTIP = 'tooltip'
PENWIDTH = 'penwidth'
URL = 'url'

DEFAULT_SHAPE = {
        ORDER: '0',
        TYPE: 'node',
        SHAPE: 'box',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: 'white',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,       
        TABLECLASS : 'table-white',
        LABEL: 'Default',
        TOOLTIP: 'Default Shape',
        }

LAYOUT = {    # ordered like in jobengine queue (errors 50+)
    'incoming': {
        ORDER: '5',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#c3e6cb',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-done',
        LABEL: 'Incoming',
        TOOLTIP: 'Incoming Collection',
    },
    'depends': {
        ORDER: '7',
        TYPE: 'node',
        SHAPE: 'box',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#e0ebeb',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-depends',
        LABEL: 'Depending',
        TOOLTIP: 'Collection depending on creation of other Collection',
    },
    'choose': {
        ORDER: '9',
        TYPE: 'node',
        SHAPE: 'underline',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#bee5eb',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-choose',
        LABEL: 'Choose',
        TOOLTIP: 'Choose Collection',
    },
    'prepare': {
        ORDER: '11',
        TYPE: 'node',
        SHAPE: 'underline',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#b0e0e6',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-prepare',
        LABEL: 'Preparing',
        TOOLTIP: 'Preparing Collection',
    },
    'stage': {
        ORDER: '13',
        TYPE: 'node',
        SHAPE: 'underline',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#b0c4de',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-stage',
        LABEL: 'Stage',
        TOOLTIP: 'Staged Collection',
    },
    'spacecheck': {
        ORDER: '15',
        TYPE: 'node',
        SHAPE: 'underline',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#d4b3f5',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-spacecheck',
        LABEL: 'Space Check',
        TOOLTIP: 'Checking available space for Collection',
    },
    'download': {
        ORDER: '20',
        TYPE: 'node',
        SHAPE: 'underline',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#dcccde',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-download',
        LABEL: 'Downloading',
        TOOLTIP: 'Downloading Collection',
    },
    'queued': {
        ORDER: '22',
        TYPE: 'node',
        SHAPE: 'underline',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#bdbdbd',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-queued',
        LABEL: 'Queued',
        TOOLTIP: 'Queued Collection',
    },
    'active': {
        ORDER: '24',
        TYPE: 'node',
        SHAPE: 'underline',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#99caff',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-jobactive',
        LABEL: 'Active',
        TOOLTIP: 'Active Collection',
    },
    'finishing': {
        ORDER: '26',
        TYPE: 'node',
        SHAPE: 'underline',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#33cccc',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-finishing',
        LABEL: 'Finishing',
        TOOLTIP: 'Finishing Collection',
    },
    'postprocessing': {
        ORDER: '28',
        TYPE: 'node',
        SHAPE: 'underline',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#99ffcc',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-postprocessing',
        LABEL: 'Postprocessing',
        TOOLTIP: 'Postprocessing Collection',
    },
    'notify': {
        ORDER: '30',
        TYPE: 'node',
        SHAPE: 'underline',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#c9d3cb',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-notify',
        LABEL: 'Notify',
        TOOLTIP: 'Notify Collection',
    },
    'done':  {
        ORDER: '40',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#c3e6cb',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-done',
        LABEL: 'Collection',
        TOOLTIP: 'Collection processing finished',
    },
    'finished':  {
        ORDER: '39',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#c3e6cb',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-done',
        LABEL: 'Collection finished',
        TOOLTIP: 'Collection processing finished',
    },
    'notrun':  {
        ORDER: '50',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#ebd9c6',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-notrun',
        LABEL: 'Not Run',
        TOOLTIP: 'Collection Not Run',
    },
    'distributed': {
        ORDER: '42',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'box3d',
        FILLCOLOR: "#c3e6cb:grey",
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-distributed',
        LABEL: 'Distributed',
        TOOLTIP: 'Distributed Collection',
    },
    'imported': {
        ORDER: '0',
        TYPE: 'node',
        SHAPE: 'cylinder',
        SHAPE_PROCESS: 'cylinder',
        FILLCOLOR: 'skyblue1',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-imported',
        LABEL: 'Imported',
        TOOLTIP: 'Imported Collection',
    },
    'temporary': {
        ORDER: '44',
        TYPE: 'node',
        SHAPE: 'note',
        SHAPE_PROCESS: 'note',
        FILLCOLOR: 'gold2',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-temporary',
        LABEL: 'Temporary',
        TOOLTIP: 'Intermediate Collection',
    },
    'archive': {
        ORDER: '45',
        TYPE: 'node',
        SHAPE: 'note',
        SHAPE_PROCESS: 'note',
        FILLCOLOR: 'grey',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'Archived',
        LABEL: 'Archived Collection',
        TOOLTIP: 'Archived Collection',
    },
    'error': {
        ORDER: '52',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#ff9980',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-error',
        LABEL: 'Error',
        TOOLTIP: 'Collection Error',
    },
    'unknown': {
        ORDER: '54',
        TYPE: 'node',
        SHAPE: 'box',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#ffffff',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-white',
        LABEL: 'Unknown',
        TOOLTIP: 'Data type unknown',
    },
    'ok': {
        ORDER: '46',
        TYPE: 'node',
        SHAPE: 'cds',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: 'palegreen2',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-done',
        LABEL: 'OK',
        TOOLTIP: 'OK',
    },
    'failed': {
        ORDER: '56',
        TYPE: 'node',
        SHAPE: 'cds',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: 'tomato',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-error',
        LABEL: 'FAILED',
        TOOLTIP: 'FAILED',
    },
    'source': {
        ORDER: '3',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'box3d',
        FILLCOLOR: 'white',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS: 'table-white',
        LABEL: 'Source',
        TOOLTIP: 'Source Collection',
    },
    'qc_report': {
        ORDER: '48',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'box3d',
        FILLCOLOR: 'yellow',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS: 'table-white',
        LABEL: 'QC Report',
        TOOLTIP: 'QC Report',
    },
    'refsamp_report': {
        ORDER: '49',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'box3d',
        FILLCOLOR: 'yellow',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS: 'table-white',
        LABEL: 'Refsamp Report',
        TOOLTIP: 'Refsamp Report',
    },
    'data': {
        ORDER: '40',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'box3d',
        FILLCOLOR: "#c6f3d1",
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'Collection',
        TOOLTIP: 'Collection containing data files or other collections',
    },
    'uploaded': {
        ORDER: '4',
        TYPE: 'node',
        SHAPE: 'folder',
        SHAPE_PROCESS: 'folder',
        FILLCOLOR: 'skyblue1',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'Uploaded',
        TOOLTIP: 'Uploaded Collection',
    },
    'invalid': {
        ORDER: '57',
        TYPE: 'node',
        SHAPE: 'cds',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: 'tomato',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-error',
        LABEL: 'Invalid',
        TOOLTIP: 'Invalid Collection',
    },
    'reference_data': {
        ORDER: '2',
        TYPE: 'node',
        SHAPE: 'folder',
        SHAPE_PROCESS: 'folder',
        FILLCOLOR: '#fdaa48',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'Reference Data',
        TOOLTIP: 'Reference dataset available in iDMS',
    },    
    'multinode': {
        ORDER: '47',
        TYPE: 'node',
        SHAPE: 'rarrow',
        SHAPE_PROCESS: 'rarrow',
        FILLCOLOR: 'lightgrey',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'Multiple',
        TOOLTIP: 'Click on to get a list of Collections', 
    },
    # shapes and colours like https://www.w3.org/TR/prov-o/diagrams/starting-points.svg
    'file': {
        ORDER: '1',
        TYPE: 'node',
        SHAPE: 'rect',
        SHAPE_PROCESS: 'rect',
        FILLCOLOR: "#fffedf",
        COLOR: "#000000",
        STYLE: 'filled, rounded',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'File',
        TOOLTIP: 'File containing information used by an Activity',
    },
    'collection_graph': {
        ORDER: '4',
        TYPE: 'graph',
        SHAPE: 'rect',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: '#c3e6cb',
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-done',
        LABEL: 'Collection',
        TOOLTIP: 'Subgraph representing a Collection (unnested)',
    }, 
    'collection': {
        ORDER: '3',
        TYPE: 'node',
        SHAPE: 'box3d',
        SHAPE_PROCESS: 'box3d',
        FILLCOLOR: "#c3e6cb",
        COLOR: DEFAULT_COLOR,
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-done',
        LABEL: 'Collection',
        TOOLTIP: 'A collection containing files or other collections',
    },     
    'database': {
        ORDER: '0',
        TYPE: 'node',
        SHAPE: 'cylinder',
        SHAPE_PROCESS: 'cylinder',
        FILLCOLOR: "#eb9494",
        COLOR: "#000000",
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'Database',
        TOOLTIP: 'Database',
    },
    'not_file': {
        ORDER: '0',
        TYPE: 'node',
        SHAPE: 'rect',
        SHAPE_PROCESS: 'rect',
        FILLCOLOR: "#ffffff",
        COLOR: "#000000",
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'No Entity',
        TOOLTIP: 'Unknown Entity, could be IP protected',
    },
    'entity': {
        ORDER: '1',
        TYPE: 'node',
        SHAPE: 'rect',
        SHAPE_PROCESS: 'rect',
        FILLCOLOR: "#fffedf",
        COLOR: "#000000",
        STYLE: 'filled, rounded',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'Entity',
        URL: 'https://www.w3.org/TR/prov-o/#Entity',
        TOOLTIP: 'An entity is a physical, digital, conceptual, or other kind of thing with some fixed aspects',
    },
    # activity according to PROV should be a rectangle with double lines on the side, but for now we use cds.
    'activity': {
        ORDER: '2',
        TYPE: 'node',
        SHAPE: 'cds',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: "#cfceff",
        COLOR: "#000000",
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'Activity',
        URL: 'https://www.w3.org/TR/prov-o/#Activity',
        TOOLTIP: 'An activity is something that occurs over a period of time and acts upon or with entities',
    },
    'process': {
        ORDER: '1',
        TYPE: 'node',
        SHAPE: 'cds',
        SHAPE_PROCESS: 'cds',
        FILLCOLOR: "#ffffff",
        COLOR: "#000000", # use for links
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'Process  \n Git Repository  ',
        TOOLTIP: 'Click to open the Git repository in a new browser tab',
    },
    'agent': {
        ORDER: '3',
        TYPE: 'node',
        SHAPE: 'house',
        SHAPE_PROCESS: 'house',
        FILLCOLOR: "#ffebc4",
        COLOR: "#000000",
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS: 'table-data',
        LABEL: 'Agent',
        URL: 'https://www.w3.org/TR/prov-o/#Agent',
        TOOLTIP: 'An agent is something that bears some form of responsibility for an activity taking place, \nfor the existence of an entity, or for another agent''s activity.',
    },
    'xsd:datetime': {
        ORDER: '1',
        TYPE: 'node',
        SHAPE: 'rect',
        SHAPE_PROCESS: 'rect',
        FILLCOLOR: "#e6e6e6",
        COLOR: "#000000",
        STYLE: 'filled',
        PENWIDTH: DEFAULT_PENWIDTH,        
        TABLECLASS : 'table-data',
        LABEL: 'Start or end time of an Activity',
        TOOLTIP: 'Start or end time of an Activity',
    },  # edges order from big to small, because they are put in a subgraph in the legend
    'solid': {
        ORDER: '6',
        TYPE: 'edge',
        ARROWHEAD: 'normal',
        NAME: 'System Edge',
        SHAPE: 'none',
        SHAPE_PROCESS: 'none',
        FILLCOLOR: 'black',
        COLOR: DEFAULT_COLOR,
        STYLE: 'solid',
        TABLECLASS : 'edge',
        LABEL: 'System Generated Edge to Entity or Activity in Graph',
        URL : '',
        TOOLTIP: 'System Generated Edge to Entity or Activity in Graph',
        PENWIDTH: DEFAULT_PENWIDTH,
    },  
    'solid_crow': {
        ORDER: '5',
        TYPE: 'edge',
        ARROWHEAD: 'crow',
        NAME: 'One to Multiple',
        SHAPE: 'none',
        SHAPE_PROCESS: 'none',
        FILLCOLOR: 'black',
        COLOR: DEFAULT_COLOR,
        STYLE: 'solid',
        TABLECLASS : 'edge',
        LABEL: 'Solid edge from one to multiple Collections in Graph',
        URL : '',
        TOOLTIP: 'Solid edge from one to multiple Collections',
        PENWIDTH: DEFAULT_PENWIDTH,
    },
    'dashed': {
        ORDER: '4',
        TYPE: 'edge',
        ARROWHEAD: 'normal',
        NAME: 'User Edge',
        SHAPE: 'rect',
        SHAPE_PROCESS: 'rect',
        FILLCOLOR: 'black',
        COLOR: DEFAULT_COLOR,
        STYLE: 'dashed',
        TABLECLASS : 'edge',
        LABEL: 'User Generated Edge to Entity or Activity inside of the Graph',
        TOOLTIP: 'Dashed User Generated Edge to Entity or Activity inside of the Graph',
        PENWIDTH: DEFAULT_PENWIDTH,
    },
    'dashed_crow': {
        ORDER: '3',
        TYPE: 'edge',
        ARROWHEAD: 'crow',
        SHAPE: 'rect',
        SHAPE_PROCESS: 'rect',
        NAME: 'One to Multiple',
        FILLCOLOR: 'black',
        COLOR: DEFAULT_COLOR,
        STYLE: 'dashed',
        TABLECLASS : 'edge',    
        LABEL: 'Dashed edge from one to multiple Collections',
        TOOLTIP: 'Dashed edge from one to multiple Collections',
        PENWIDTH: '2',
    },
    'dotted': {
        ORDER: '2',
        TYPE: 'edge',
        ARROWHEAD: 'normal',
        NAME: 'Outside Graph',
        SHAPE: 'rect',
        SHAPE_PROCESS: 'rect',
        FILLCOLOR: 'black',
        COLOR: DEFAULT_COLOR,
        STYLE: 'dotted',
        TABLECLASS : 'edge',
        LABEL: 'Edge to Entity or Activity outside of the Graph. Increase Graph Levels to see more Collections',
        TOOLTIP: 'Dotted Edge to Entity or Activity outside of the Graph. Increase Graph Levels to see more Collections',
        PENWIDTH: '2',
    },
    'dotted_crow': {
        ORDER: '1',
        TYPE: 'edge',
        ARROWHEAD: 'crow',
        NAME: 'Outside Graph',
        SHAPE: 'rect',
        SHAPE_PROCESS: 'rect',
        FILLCOLOR: 'black',
        COLOR: DEFAULT_COLOR,
        STYLE: 'dotted',
        TABLECLASS : 'edge',
        LABEL: 'Dotted edge from one to multiple Collections',
        TOOLTIP: 'Dotted edge from one to multiple Collections',
        PENWIDTH: '2',
    },
}